wandb_version: 1

name:
  desc: null
  value: optimize SVM
method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
    goal: minimize
    name: avgloss
parameters:
  desc: null
  value:
    batchsize:
      min: 32
      max: 64
    lr:
      min: 2.0e-05
      max: 0.02
    gamma:
      min: 0.9
      max: 0.9999
    EPS_START:
      min: 1
      max: 100
    EPS_DECAY:
      min: 1000
      max: 100000
    EPS_END:
      min: 5.0e-05
      max: 0.05
    WARMUP:
      min: 100
      max: 50000
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718422811.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.14
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
EPS_DECAY:
  desc: null
  value: 74814
EPS_END:
  desc: null
  value: 0.027738018873586928
EPS_START:
  desc: null
  value: 47
WARMUP:
  desc: null
  value: 1650
batchsize:
  desc: null
  value: 54
gamma:
  desc: null
  value: 0.9635069456358016
lr:
  desc: null
  value: 0.009560481082822129
